# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ce1ff7e8c279e41c8317e06da0a8aff07bcd64db1c9335ef4f02605014880a61f23708e18ab9979f45dddb14605ee1e18e8a3573e22783cd2caffc8d2a17989

test:
  secret_key_base: 898e50eaad5eb77438e9887d1b19085c72559a2d5c3d9e2a84f0c546f3365607f6d9203940044ba03bcf77f686f7a71ece84c54686cb2f7467428513184c342b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
